module.exports.authController = require('./auth.controller');
module.exports.userController = require('./user.controller');
module.exports.fooditController = require('./foodit.controller');
module.exports.homeserviceController = require('./homeservice.controller');
module.exports.beautyzoneController = require('./beautyzone.controller');
module.exports.geolocationController = require('./geolocation.controller');
module.exports.cardController = require('./card.controller');
module.exports.analyticsController = require('./analytics.controller');
// module.exports.notificationController = require('./notification.controller');
